### ISSUE TITLE
PHP error on the live site

### ISSUE THREAD

**Issue by willkirkby** [MathsJam/mathsjam-site#103] opened 2018-01-21 20:23 UTC
<img width="1556" alt="screen shot 2018-01-21 at 20 22 36" src="https://user-images.githubusercontent.com/2166769/35198586-ea75fb64-fee8-11e7-9fa3-de9a901ad293.png">

**Comment by katiesteckles** [comment] 2018-01-22 08:49
This is fixed now! It was caused by an invisible nbsp character in the Leeds file, which may have been anyone's fault.

**Closed by katiesteckles** 2018-01-22 08:49 UTC
